# Increase the memory available to gradle or else it explodes
org.gradle.jvmargs=-Xmx6G

minecraft_version=1.20.4

# Fabric: https://fabricmc.net/develop/
fabric_loader_version=0.16.10
fabric_api_version=0.97.2+1.20.4

# AMECS, on fabric: https://maven.siphalor.de/de/siphalor/
# Todo, looks like AMECS isn't on 1.21 !
amecsapi_artifactid=amecsapi-1.20
amecsapi_version=1.5.0+mc1.20-pre1

amecs_artifactid=amecs-1.20
amecs_version=1.3.9+mc.1.20-pre2

nmuk_artifactid=nmuk-1.20
nmuk_version=1.1.0+mc1.20-pre2

# Neofrog: https://maven.neoforged.net/#/releases/
neoforge_version=20.4.239

# my own versions
#TODO update this in neoforge.mods.toml since substitution is broken, and the piece of shit
#intentionally crashes when the version string is ${version}.
version = 2.0.3
group = agency.highlysuspect
mod_name = rebind_narrator
